### PR TITLE
feat: increase coverage across the board and include enums for readability

### PR DESCRIPTION
**Pull request by petrovska-petro**
Tackles the finding in this [doc](https://github.com/GalloDaSballo/badger_governance_veto/blob/feat-review-alex/Findings.MD)

Coverage has being improved up to 94%

Screenshot 2022-11-01 at 00 29 51

**Note:** also it includes a new argument in schedule and scheduleBatch methods, which will help for the context of the proposed transaction. It can be leverage later on the governance portal to fill it up the ui, interpreting the markdown in the string. This argument is not passed in the executions, since it is not needed to create the hash.

### CODE REVIEW

**Comment by GalloDaSballo** [comment]
What's the rationale behind allowing a 0 delay to queue operations?

Shouldn't a minimum delay be enforced at the code level?

Update: There's a field `minDelay` but is unused

**Comment by GalloDaSballo** [comment]
Also not getting a revert here
https://github.com/Badger-Finance/badger_governance_veto/blob/9195b344e3f1a0a29dee98000013d85008839275/tests/test_batching.py#L243-L244

```python
    with reverts("TimelockController: underlying transaction reverted"):

```

Screenshot 2022-11-08 at 16 19 49

Any advice?

**Comment by petrovska-petro** [comment]
> Enforce delays onchain and adapt test accordingly

this is resolved in bb563f18021b7584bd0e107faf0a45f534af35ee

**Comment by petrovska-petro** [comment]
> What's the rationale behind allowing a 0 delay to queue operations?
> 
> Shouldn't a minimum delay be enforced at the code level?
> 
> Update: There's a field `minDelay` but is unused

this is resolved in bb563f18021b7584bd0e107faf0a45f534af35ee

**Comment by petrovska-petro** [comment]
> Also not getting a revert here
> 
> https://github.com/Badger-Finance/badger_governance_veto/blob/9195b344e3f1a0a29dee98000013d85008839275/tests/test_batching.py#L243-L244
> 
> ```python
>     with reverts("TimelockController: underlying transaction reverted"):
> ```
> 
> Screenshot 2022-11-08 at 16 19 49
> 
> Any advice?

locally it is jumping the revert for me in the test. SS of the test in latest commit bb563f18021b7584bd0e107faf0a45f534af35ee

Screenshot 2022-11-09 at 16 18 07
Screenshot 2022-11-09 at 16 18 38

**Pull request merged**
